def getimagepallette():


	images = {}

	images["flame_base"] = "board"
	images["flame_0R"] = "board"
	images["flame_1R"] = "board"
	images["flame_2R"] = "board"
	images["flame_3R"] = "board"
	images["flame_4R"] = "board"
	images["flame_5R"] = "board"
	images["flame_6R"] = "board"
	images["flame_7R"] = "board"
	images["flame_8R"] = "board"
	images["flame_9R"] = "board"
	images["flame_10R"] = "board"
	images["flame_11R"] = "board"
	images["flame_12R"] = "board"
	images["flame_0L"] = "board"
	images["flame_1L"] = "board"
	images["flame_2L"] = "board"
	images["flame_3L"] = "board"
	images["flame_4L"] = "board"
	images["flame_5L"] = "board"
	images["flame_6L"] = "board"
	images["flame_7L"] = "board"
	images["flame_8L"] = "board"
	images["flame_9L"] = "board"
	images["flame_10L"] = "board"
	images["flame_11L"] = "board"
	images["flame_12L"] = "board"
	images["flame_snooze"] = "board"
	images["flame_disable"] = "board"
	images["egg_timer"] = "board"
	images["start_disabled"] = "buttons"
	images["slider_outline"] = "buttons"
	images["timer_Next"] = "buttons"
	images["timer_30"] = "buttons"
	images["timer_60"] = "buttons"
	images["timer_120"] = "buttons"
	images["timer_180"] = "buttons"
	images["timer_Lock"] = "buttons"
	images["button_outline"] = "buttons"
	images["large_button_outline"] = "buttons"
	images["cancel"] = "buttons"
	images["commit"] = "buttons"
	images["configure"] = "buttons"
	images["return"] = "buttons"

	return images
