def getimagepallette():

	images = ("flame_base",
				"flame_0R",
				"flame_1R",
				"flame_2R",
				"flame_3R",
				"flame_4R",
				"flame_5R",
				"flame_6R",
				"flame_7R",
				"flame_8R",
				"flame_9R",
				"flame_10R",
				"flame_11R",
				"flame_12R",
				"flame_0L",
				"flame_1L",
				"flame_2L",
				"flame_3L",
				"flame_4L",
				"flame_5L",
				"flame_6L",
				"flame_7L",
				"flame_8L",
				"flame_9L",
				"flame_10L",
				"flame_11L",
				"flame_12L",
				"flame_snooze",
				"flame_disable",
				"egg_timer",
				"start_disabled",
				"slider_outline",
				"button_outline")
	return images
